### ISSUE TITLE
Roland XS-62S Switcher control

### ISSUE THREAD

**Issue by a1whittaker** [bitfocus/companion-module-roland-xs62s#1]
**Describe the feature**
Control of Roland XS-62S Switcher - Similar to the Barco PDS902

**Is this platform dependent (windows, mac, ..)?**
Not dependent.

**If documentation is required to implement, do you know where to find it?**
The Owners manual has the RS232/Lan commands - https://proav.roland.com/global/products/xs-62s/support/

**Usecases**
The switcher is becomming more commen in the events area. Very helpful to have to compliment the software program that Roland have put out for the switcher.

**Comment by josephdadams** [comment]
I am currently writing this module. @a1whittaker , are you available to test this?

**Comment by josephdadams** [comment]
@a1whittaker, download this into your development environment and let me know when it is tested. Thanks!

**Comment by krocheck** [comment]
@a1whittaker we'll need to you to test this module, as it was based on the V-60HD but the two have some different specifications.  If you need an Win or Mac installer, you can find it at https://builds.bitfocus.io/companion/ and you're looking for build #1375 or higher (or just download 'latest').

Let us know if it works out.  Thanks!

**Comment by a1whittaker** [comment]
Works a treat! Thanks! For basic operation it is what I needed.
