### ISSUE TITLE
Roland XS-62 Audio Delay Feature

### ISSUE THREAD

**Issue by a1whittaker** [bitfocus/companion-module-roland-xs62s#2]
In certain cases I have found I need to adjust the audio delay of my input to it syncs on the output screens. Being able to control the audio delay from the stream deck would be great, it would only need to be incriments of 0.1 up to 12 frames.

**Comment by josephdadams** [comment]
Closing this because it is implemented for the analog audio inputs, and not possible to control on the SDI/HDMI inputs.
