### ISSUE TITLE
"Set DSK on/off" for Roland XS-62S not working

### ISSUE THREAD

**Issue by RCI-ET** [bitfocus/companion-module-roland-xs62s#4]
Hi all,
The "set DSK on/off" command doesn't seam to work in the Roland XS-62S module. 
Every other command I need is working fine. I hope someone can help me with the DSK command.
Thank you!

**Comment by josephdadams** [comment]
Fixed. Typo in the protocol statement. I’ll get it updated in the core and you’ll have to download a new build.
